(atx_heading) @keyword
(setext_heading) @keyword
(fenced_code_block) @string
(indented_code_block) @string
(code_fence_content) @string
(info_string) @module
(block_quote) @comment
(thematic_break) @punctuation
(link_label) @function
(link_destination) @string
(link_title) @string
(link_reference_definition) @function
(list_marker_minus) @operator
(list_marker_plus) @operator
(list_marker_star) @operator
(list_marker_dot) @operator
(list_marker_parenthesis) @operator
(task_list_marker_checked) @constant
(task_list_marker_unchecked) @variable
(html_block) @tag
(fenced_code_block_delimiter) @punctuation
